### ISSUE TITLE
New permissions since migration to Hilt

### ISSUE THREAD

**Issue by koppen37** [sduduzog/slim-launcher#109]
Hi @sduduzog , 

Just noticed that the newly updated versions (both play store and f-droid) have new permissions, for storage and telephone. They are never used/asked for it seems, but users might find it odd that these extra permissions showed up. 

Tried finding the commit that introduced these permissions using `git bisect` and this gives 36942a458138a20782e9b3f3946995215e685155. [This](https://www.reddit.com/r/android_devs/comments/ic0wmq/is_dagger_is_adding_write_external_storage_and/) discusses that it should already be fixed upstream, haven't had the time to test this out myself yet.

**Comment by sduduzog** [comment]
I thought it was some weird glitch when I first saw it. It's weird that a tool can add stuff to what goes to the app, and especially something coming from google
