### ISSUE TITLE
Just Play Store and Settings available in app list

### ISSUE THREAD

**Issue by faxesystem** [sduduzog/slim-launcher#116]
Installed Slim Launcher today with F-Droid on my Pixel 2 running Android 11. 

When trying to add apps I can just choose from Settings and Play Store. Also nothing comes up when using the search function.

![Screenshot_20200925-082022](https://user-images.githubusercontent.com/17175964/94233648-82f2e880-ff08-11ea-9217-1aad7488bdec.png)

**Comment by fusion44** [comment]
Looks like Android 11 changed how to query installed apps:
https://proandroiddev.com/how-to-get-users-installed-apps-in-android-11-b4a4d2754286

**Comment by faxesystem** [comment]
Unlauncher is working without problems. https://github.com/jkuester/unlauncher

**Comment by koppen37** [comment]
@fusion44 Thnx for the link, adding this permission indeed seems to solve this problem. Opened a PR based on this.

Unlauncher still uses the old way to find/launch apps which doesn't support work profile, but apparently still allows you to query all the apps without any additional permission on android 11. 
@sduduzog Not sure what you think about this new permission needed query all the apps, tested some other solutions today but see no way around it (using `LauncherApps`).

**Comment by sduduzog** [comment]
Its a pretty straight forward permission, if it fixes our issue, I'm happy with it. I do have to update the privacy policy for it soon though

**Comment by sduduzog** [comment]
it was a very drastic move from google to do something like this with no warning. 

I'll prepare a release tonight, it'll probably take 2-4 days for google play to review the app,
