### ISSUE TITLE
Feature Request: App search in the "Slim options" menu

### ISSUE THREAD

**Issue by uzluisf** [sduduzog/slim-launcher#12]
While I like the idea of having only five apps in the home screen, sometimes I find myself wanting to open a certain app (e.g., calendar, clock, file manager, etc.) that is not among the home screen apps. As of now, the only way to access it is by replacing one of the home screen apps with it and this can be quite tiring if one has to do it often.

I'm using [KISS Launcher](https://kisslauncher.com/) and it has a nifty app search feature. Even if it's disabled by default, I think the same feature could be provided in Slim Launcher.

**Comment by sduduzog** [comment]
Ok I just downloaded KISS launcher and I'll use it for some time. I definitely saw what you were talking about. I'll also try to reach out for help in minimising the app size, I still don't believe they kept it under 250kb.

**Comment by usakuja** [comment]
niagara launcher(peter hurber) is also a very similar purpose serving launcher when compared to kiss launcher.
app size is not maintained.but serves as a full time launcher.
but kiss and niagara is not as minimal as slim launcher is.

**Comment by uzluisf** [comment]
@usakuja Niagara looks quite sleek. I used to be quite invested in customizing android with launchers. Nowadays, I fairly happy with a launcher that gets rid of the clutter of Android default launchers, allow me to place some apps in the homescreen and search those apps I might need from time to time. I think this is where Slim Launcher excels.

Another simple launcher is [Light Android Launcher](https://f-droid.org/en/packages/com.github.postapczuk.lalauncher/). It has just a homescreen with some favorite apps and the rest of the apps are a left swipe away.

**Comment by esmoak** [comment]
@sduduzog if you are researching search launchers to possibly implement a similar function into your launcher, this app is a launcher (or standalone app) which is only 51 KiB. Lighter than KISS.

https://github.com/ligi/FAST

FASTer App Search Tool (Find apps just by typing) - https://f-droid.org/app/org.ligi.faster

**Comment by esmoak** [comment]
I wanted to add that I think a sleek way to implement a search feature, if you choose to, is either select a gesture or let the user choose one to launch the search .

So double tap the screen to have search pop up or swipe left/right.

An icon is okay too, but no icon is more simple looking. 

Or just add a gesture option to launch an app of our choosing and we could have something like the app I mentioned in the post before this to launch for a search.

I think this launcher is smooth and beautiful, but I think it is unrealistic to have five apps with no easy access to other ones. 

Best wishes on job hunting and success. You've proven you can make a fine app.

**Comment by mattcoxonline** [comment]
Having come here to ask for the same feature, I am somewhat mixed opinion on this one.

I currently narrowed my apps down to my top five - but reserved that fifth space for the _Finder_ app. The _Finder_ app is Samsung's device search.

<img src="https://user-images.githubusercontent.com/673542/53177843-080d7180-35f1-11e9-827e-c37f44be2ac5.jpeg" width="250" />

If I were to have a search functionality, I would much prefer it to be not one of the Top 5 options. I like the idea of a gesture - as suggested by @esmoak. A swipe up, or down, or left, or right.

That said... having a search is almost counter to why I am using this app - to use my phone less. It's incredibly useful to get to the apps I use once in a while rather than have them in accessible. But I also use it regularly to search for Instagram. One of the apps I wanted to use less.

**Comment by sduduzog** [comment]
I'm closing this issue in favour of issue [#14](https://github.com/sduduzog/slim-launcher/issues/14)

**Comment by sduduzog** [comment]
@mattcoxonline I've procrastinated for too long on that one. **Gestures**! But before them, I have issues with the bottom options drawer. It seemed convenient at the beginning but it made the app seem heavy, for some reason. I'm working on a beta that has no sense of stacked layers (the bottom sheet drawer), and a simple gesture for showing more or fewer apps.
