### ISSUE TITLE
Date shows incorrectly

### ISSUE THREAD

**Issue by jakeg** [sduduzog/slim-launcher#122]
![Screenshot_20201105-202657](https://user-images.githubusercontent.com/744792/98292858-51f4e180-1fa5-11eb-88aa-210be1fbde27.png)

Should say "Thu 5th Nov" but instead says "Thu, M11 05"

**Comment by sduduzog** [comment]
oof, thats bad

**Comment by chuckcarroll** [comment]
Can confirm same issue on Graphene OS/Android 11.
