### ISSUE TITLE
Text positioned underneath the status bar

### ISSUE THREAD

**Issue by uzluisf** [sduduzog/slim-launcher#13]
Please look at the images. This is on a Samsung GS6.

![slim-options](https://user-images.githubusercontent.com/22332927/52183140-e6c81b00-27d2-11e9-873e-0e5ad44cc202.jpg)
![apps](https://user-images.githubusercontent.com/22332927/52183141-e7f94800-27d2-11e9-9430-966ca653655b.jpg)

**Comment by sduduzog** [comment]
I carelessly added a 'hide status bar' feature without a thorough test. This is embarrassing

**Comment by uzluisf** [comment]
Nothing to be embarrassed about, man! Things happen :smiley:!

This is a pretty cool app.

**Comment by sduduzog** [comment]
I'll most likely fix this after I finish with a beta. I'm working on it locally and it brings a couple of ui changes
