### ISSUE TITLE
Rename does not work

### ISSUE THREAD

**Issue by DerBeutlin** [sduduzog/slim-launcher#16]
First of all thanks a lot for this great launcher.
I think I found i minor bug:
In the preferences I can press long on the name of each app and I'm asked to rename the app. However the cursor seems to be outside of the text field and although I can change the text, this change is not saved when I press enter.

**Comment by sduduzog** [comment]
Thats odd... I'll check it out soon

**Comment by DerBeutlin** [comment]
Ok I think I just don't see the button in my app.. When I click the (for me invisible) button everything works correctly
