### ISSUE TITLE
[Feature Request] Tap area include whole row app occupies

### ISSUE THREAD

**Issue by esmoak** [sduduzog/slim-launcher#18]
It would be nice if the tap area for each app was the whole row the app occupies so the app text doesn't have to be tapped directly each time. 

Edit: A workaround is to rename the app with an adequate amount of spaces after the app name. 

@sduduzog thanks again for your launcher. Since there is a workaround that doesn't require actually changing the app code, feel free to close this issue unless you think it fits into your app philosophy and that it's something you want to consider.

**Comment by caigo1** [comment]
I just opened a Github account exactly for suggesting this same feature. :)
It would be nice indeed, especially on bigger screens.

**Comment by esmoak** [comment]
I just realized a workaround for this is to just rename the app with a bunch of spaces after the name. 

I think there are potential positives for leaving the setup like it currently is, such as more accurate presses/less accidental app launches. And if the dev wants to leave space for other future options.

**Comment by caigo1** [comment]
> 
> I just realized a workaround for this is to just rename the app with a bunch of spaces after the name.
> 
That's a good idea, thank you!
Of course, this actually changes the behaviour of the app only on the main launcher screen, while the items in "Slim options" are still tappable only on the text area.
I'm quite happy with the workaround at the moment anyway. :)

> I think there are potential positives for leaving the setup like it currently is, such as more accurate presses/less accidental app launches. And if the dev wants to leave space for other future options.
Making the whole row select the item would be nice for uniforming the behaviour of the app to other apps, I acknowledge what you say as an option though.

@sduduzog I take the chance too for thanking you for the app: I've been using it for a few days only, and I'm liking it quite a lot. It's also running pretty well on an old phone I just upcycled, actually better than the original Trebuchet launcher. Thank you!

**Comment by sduduzog** [comment]
@esmoak I'm really sorry you have to go through weird hacks to achieve this behaviour. Currently the reason why I wrapped keytouch events to the app name is because I wanted the layout to catch the rest of the touch gestures for future possible features. This however might be changed.

@caigo1 thanks for using the app. Also github might even become a cool tool for you, we'll never know. Also, with a bigger screen, do you mean a tablet? I'd like to see how the launcher looks like on one

**Comment by esmoak** [comment]
@sduduzog You absolutely have no reason to apologize. It's a spectacular launcher as it is with a great design philosophy. 😀
Jeep up the great work and best wishes.

**Comment by caigo1** [comment]
@sduduzog Actually not, I just tried it on my small-ish phones (<5”). Sometimes I don't find the items on the right side to be reachable only using my right hand (the same one I use for holding the phone), and I just thought the issue could be worse with bigger screens. I had no chance to these the launcher on tablets unfortunately.

Keep up the  good work!

**Comment by sduduzog** [comment]
**UPDATE**
Progress has been really slow up until yesterday. Next beta will have the whole row clickable. On top of that. I'm checking how complex it will be to allow for configuring aligning text to the right of the screen. This so far I've achieved when the whole row is filled using `Gravity.END` with each text view, being rather redundant. I'll moslty end up with whole row clickable. I'll try to get these changes out to the stable release and the beta in probably a weeks time or more. I just sold my laptop 0_o

**Comment by caigo** [comment]
Wow, thank you!
One thing I'm really liking about the app is actually your approach towards developing and the nice steady collaboration among you and the users! I have no knowledge at all on programming, but hope I'll be useful in submitting bug records and so. :)
Good luck with the job search!

**Comment by sduduzog** [comment]
Guess what. I'm starting my first job on the first of March 🎉🥳🥳

**Comment by sduduzog** [comment]
Hi there, please look out for the beta version, I know this is very late though

**Comment by caigo** [comment]
Hi there, thanks!
I'm just using F-Droid as an app repo/store and have no Google account (in general nor linked to my phone), so I think I could not access the beta through the Play store. I'm sorry!
Do you think there's any way of testing directly through an apk?
Thank you and sorry for the inconvenience!

**Comment by sduduzog** [comment]
This took some time but https://github.com/sduduzog/slim-launcher/commit/4bd41ef8d1e88567121dcfa16bc1a37f8e91176c sorts this out
