### ISSUE TITLE
[Feature request] add in app purchase

### ISSUE THREAD

**Issue by mohammadanton** [sduduzog/slim-launcher#20]
I would like to support this project even only 1$ but i cant because the only way to support is with buymeacoffe, which is good but not for people like me who not have credit card.

**Comment by sduduzog** [comment]
I actually have a buyme a coffee link now. I'm not really focused on making major moola from it but apparently it's really exciting getting a notification from it 🤣 

I'm closing this now, Also please check out the beta release, you have to opt in as a tester though. I need all the feedback I can get before I push changes to production. That's also worth a thousand bucks ;)
