### ISSUE TITLE
Bug: Clock intermittenly fails to display some digits 

### ISSUE THREAD

**Issue by oxogglant** [sduduzog/slim-launcher#23]
I have noticed a few times some digits missing from the clock face. 

Phone: Moto G4 Plus-- Android 7.0
Release: 2.3.0-beta3
![Screenshot_20190426-100129](https://user-images.githubusercontent.com/10355223/56822082-41d74000-680d-11e9-9159-79c6dce4422a.png)

**Comment by joseguerrerogallego** [comment]
Same here, at 10:03AM in 2.3.0-beta3 and prior stable release in F-Droid

**Comment by kalavo** [comment]
Also had the same issue with the Date.


![](ftp://10.1.1.102:2211/Pictures/Screenshots/Screenshot_20190427-103947_Slim_Launcher.png)

![](ftp://10.1.1.102:2211/Pictures/Screenshots/Screenshot_20190428-081103_Slim_Launcher.png)

![](ftp://10.1.1.102:2211/Pictures/Screenshots/Screenshot_20190501-224137_Slim_Launcher.png)

**Comment by kalavo** [comment]
Also had the same issue with the date.

![Screenshot_20190427-103947_Slim_Launcher](https://user-images.githubusercontent.com/50033853/57050884-113a4f00-6cc2-11e9-9592-93b05b7aafd0.png)
![Screenshot_20190428-081103_Slim_Launcher](https://user-images.githubusercontent.com/50033853/57050894-15ff0300-6cc2-11e9-8c4b-e9fad6828759.png)
![Screenshot_20190501-224137_Slim_Launcher](https://user-images.githubusercontent.com/50033853/57050903-1a2b2080-6cc2-11e9-8bb4-ccd2e51d488a.png)

**Comment by sduduzog** [comment]
I haven't been able to reproduce this since it was raised and I made changes to the code. What was bothering me is that I couldn't figure out why it was happening. Changes I've made since this issue was opened will allow for easier investigation should it still be apparent. Thanks again for raising this, I would have totally ignored it if no one did
