### ISSUE TITLE
Stepping away from what I liked about this launcher

### ISSUE THREAD

**Issue by kalavo** [sduduzog/slim-launcher#24]
Loved that this was just a launcher. The tasks feature has been done on other minimalist launchers... if I want tasks, I’d rather it be a separate app. Likewise notes.

The option of an additional two apps is a welcome feature, but would prefer not to have to scroll for them. Tasks now hides app 5.

The scroll up to options is cleaner than the ^.

The phone and camera icon could be bigger to better match the text.

**Comment by oxogglant** [comment]
I don't mind the "Notes and Tasks" features being integrated into the launcher for people who may want them, but like @kalavo I have my own apps that I'm already using. I'd like the option to be able to toggle off the Notes and Tasks buttons in the launcher and instead add the apps I already use.

**Comment by sduduzog** [comment]
You know, in actually drawn to creating these apps as standalone after reading this.

**Comment by sduduzog** [comment]
Specifically, a notes, audio and maybe tasks even 🤔 but in all honesty, I did stray these past weeks. I was actually very excited 😅
