### ISSUE TITLE
Logo Contribution

### ISSUE THREAD

**Issue by revilationer** [sduduzog/slim-launcher#26]
Hi!
I am a graphic designer
If your app needs a logo i can help you
I will be waiting for your reply to start :)

**Comment by sduduzog** [comment]
I didn't think I did but now I'm interested in seeing what you would have made it look like. If you can pull it off and it gets great feedback, I'd actually do a rebrand

**Comment by sduduzog** [comment]
https://developer.android.com/google-play/resources/icon-design-specifications
