### ISSUE TITLE
24h time sometimes cut off

### ISSUE THREAD

**Issue by JustMeErazem** [sduduzog/slim-launcher#29]
I'm using Slim Launcher 2.3.2 from F-Droid. Since switching to 24h time, the last digit (eg. 12:3x) sometimes gets cut off (eg. It shows 12:3). Once I even saw part of a digit (it was cut in half).

Example screenshot:

![Screenshot_Slim_Launcher_20190520-100808](https://user-images.githubusercontent.com/46302511/58021391-104f4d00-7b0b-11e9-926c-0d2986826c47.png)

Most of the time it works fine though, this issue only happens sometimes.

Edit: Example of the last digit being cut off:

![Screenshot 2](https://i.ibb.co/SX5J4cL/Screenshot-Slim-Launcher-20190520-184648.png)

**Comment by sduduzog** [comment]
I thought I had this fixed. I'll give it another go 👍

**Comment by sduduzog** [comment]
Please reopen should this come up again. No code changes were made to fix this. I just updated the app dependencies and the dust settled a bit. I do not want to assume that this is fixed.
