### ISSUE TITLE
Feature Request: non invasive notifications

### ISSUE THREAD

**Issue by pseudotrue** [sduduzog/slim-launcher#31]
Hi!

I think it would be a good idea to provide a low impact notification method. I had this idea, but I have no clue how hard this would be to implement since I’m not a technical person. But just in case it serves you...

My idea is this: keep the main interface just as it is (is so sleek) and when you got a notification from an app change the color of the characters, for example to red or maybe to a color that fits with the theme in use, so you’ll have the same main interface with the name of your apps in white except for one or two in red with the notifications. I attach an example.

I think it can look really cool and it would have a low visual impact while at the same time would allow an efficient method for you to check out if you have notifications right away.

Keep up the good work!
![871f5179-Slide3](https://user-images.githubusercontent.com/51478052/59097415-c4c7dc00-891d-11e9-9333-23ad2227e7f6.JPG)

**Comment by Mikaela** [comment]
I am not sure changing colour would be a good idea. I am using my phone in [monochrome display mode](https://gogray.today/android) in hopes to use it less and at times things like colour change become unreadable and I think this could be an accessibility issue for colourblind people (testing which is probably the point of that feature).
<br/>
I clicked this issue thinking that you would be requesting something that requires notification access permission and to hope that the feature would be hidden from users of Android Go for whom the OS only displays a message that the feature cannot be enabled on this phone.

**Comment by semente** [comment]
I would suggest using dots instead changing the color. 

Like the one in the screenshot, but greyish.

![2019-07-19-175511_91x60_scrot](https://user-images.githubusercontent.com/29862/61565092-874f8600-aa67-11e9-81a7-1d7337f2fa46.png)

**Comment by sduduzog** [comment]
It's quite interesting that the very first person to test the app, after me, requested the same thing. But however, with this app, I hope to approach a minimalism cult like approach with every feature coming in. The only notification I might end up displaying might only be from missed calls and text messages.

Secondly, I'm trying to run away as much as possible from features that require permissions unless it's blocking my progress (e.g. launching the clock app requires `SET_ALARM` permission)

This https://github.com/sduduzog/slim-launcher/issues/14 might be of interest in context. With different context i.e. zen mode might not have such notifications but the other mode(s) might.
