### ISSUE TITLE
Custom apps disappear after reboot

### ISSUE THREAD

**Issue by MattWill10000** [sduduzog/slim-launcher#32]
Hi sduduzog, excellent work on this launcher!
I have an issue with it : after I reboot the phone, the custom apps disappear. I have to go to the option menu, customize apps, they appear there. When I go back on the main screen they're back again.
Keep up the good work!

**Comment by MattWill10000** [comment]
Sorry, mate, f-droid just showed me the update and after installation the problem didn't appear again. I'm closing the ticket.

**Comment by sduduzog** [comment]
I bet that was the androidx update that solved it. Thanks for the heads up
