### ISSUE TITLE
App not accessible [maybe more than one?]

### ISSUE THREAD

**Issue by DC7IA** [sduduzog/slim-launcher#34]
Hey there,

thanks for this project. While adding apps, I noticed I could not find using the app search.

I'm trying to add my calendar: https://f-droid.org/en/packages/ws.xsoh.etar/

For some reason that won't work. I can find [all?] other apps. The apps I needed, I could add this way, but Etar for some reson does not show up.

**Comment by Mikaela** [comment]
I was unable to find Google Calendar and later I learned it was because touching the date already opens it up. Does trying it open Etar for you?

**Comment by DC7IA** [comment]
That's quite counter-intuitive. I suggest instead letting the user add it, but also display a message like "You can also reach [app name] by simply touching the date. Do you want to add [app name]?" which could be answered with yes/no. Or something similar. I've literally tried to add the calendar for half an hour. :D

**Comment by sduduzog** [comment]
I'm really horrible at communicating 😂😂😂 @DC7IA  I do however understand the approach you are implying. I'll try it out and see how far I go.

**Comment by sduduzog** [comment]
Hey, this was actually resolved. I'm closing the issue now
