### ISSUE TITLE
Notes, adjust font size, battery show and translate day's name

### ISSUE THREAD

**Issue by aliakcky** [sduduzog/slim-launcher#35]
Hi bro. Please this specs have to your app. Sorry bad english.

**Comment by semente** [comment]
About battery info, there is an issue for that #25.

I also would to have the ability to change the font size and quick notes or tasks with checkbox. But the best is to create a new issue for each new feature request. If you don't mind I'm doing this then we can close this one.

**Comment by sduduzog** [comment]
### Notes
- I will not do. I prefer tasks over notes. I did implement them in the past and removed them early this year. I prefer you choose Keep or your preferred choice, sorry.

### Adjusting font size
- This might happen. I first want to start with bundling a default font for the app. Then work from there

### Battery status
- Yes, this is in the works

### Translations
- I have a bunch of request in my emails from people who are willing to help me with translating the app. The problem so far is that not all of them are familiar with android studio and github. I'm still trying to find solutions for that but it is coming also.

Thank you for raising these issues
