### ISSUE TITLE
Ability to change the font size

### ISSUE THREAD

**Issue by semente** [sduduzog/slim-launcher#36]
Also I think the line spacing is too high.

**Comment by sduduzog** [comment]
What I'm planning to do is have one default font. Currently, I think to allow various fonts will have abnormal text scaling issues which also is what is happening as different phone manufacturers have different default fonts.

The font I'm looking into is **Ubuntu**. I'll study the license andif it's usable, I'll bundle it with the app as the default

**Comment by semente** [comment]
The new font looks good :0

**Comment by juliangaal** [comment]
Hi, thanks for making this great launcher! I'm really enjoying it

As far as I understood from your top comment, the Ubuntu font is now the default. With this hurdle out of the way, have you thought about allowing different font sizes? Maybe as part of the theme menu?
