### ISSUE TITLE
Code Contribution

### ISSUE THREAD

**Issue by parshav** [sduduzog/slim-launcher#40]
Hey, 
Huge fan of the app, I would love to be able to contribute code to this project. In your readme you mention a `develop` branch but I don't think you've exposed that on the repository. If I wanted to contribute by code (thinking just minor cleanups / kotlin stuff) would that be possible ? 
Thanks !

**Comment by sduduzog** [comment]
Hi, I'd appreciate that a lot. I've just republished a new `develop` branch based on master. Shout if you need anything else 👍
