### ISSUE TITLE
[Feature Request] add double tap to screenlock or sleep feature

### ISSUE THREAD

**Issue by sduduzog** [sduduzog/slim-launcher#42]

**Comment by aliakcky** [comment]
I want it. :)

**Comment by sduduzog** [comment]
To whomever picks this up, this will require some reading and more so, some pretty good writing for the feature to comply with google's android app policies as this feature requires permission of high privacy/security risk. I've had attempted it before and the app was suspended from Google play for almost a week pending a fix.
