### ISSUE TITLE
[Feature Request] Allow auto-rotate, enable landscape mode

### ISSUE THREAD

**Issue by sduduzog** [sduduzog/slim-launcher#45]
Requested via email by Abbi Bramble

>A major downside to that is even though they allow maps to work the whole auto rotate fuction of the phone stops working meaning I can not use it as a satnav in my car holder!

**Comment by sduduzog** [comment]
This was added in previous versions but the reception was not pleasant... 

If anyone has had experiences similar to the quote on the above comment, please reopen

**Comment by KaKi87** [comment]
Hello,
I have a tablet on which I'd like to use this launcher but landscape mode is absolutely required.
However, this quote doesn't seem relayed to this project ?
Thanks

**Comment by sduduzog** [comment]
@KaKi87 I think for such issues, its more than just landscape mode. Work needs to be put in to layouts specifically for large screens

**Comment by KaKi87** [comment]
Well, until it gets implemented, I used a "rotation manager" app that enforces landscape globally, and it works.
