### ISSUE TITLE
Messages shortcut

### ISSUE THREAD

**Issue by BenTearzz** [sduduzog/slim-launcher#47]
Currently at the top there's a shortcut to the alarms by clicking on the time.
At the bottom there's the phone and camera.

Between the phone and camera it would be really really nice to have message icon in the middle, so that I don't need to have both Messages and Messenger added to the home screen.

**Comment by sduduzog** [comment]
Although it would be something I would have considered in the past. I don't feel this could be the direction the project would take. Already I'm not comfortable with the call and camera icons, I wish I could just remove them, it would be counterintuitive for me to add a third. Remember our enemy is clutter and we have to do everything to keep it at a minimum

**Comment by BenTearzz** [comment]
I still think an option to change the limit would be nice, I love this homescreen, but it simply doesn't have enough room.

Currently I have the following:

- Authy _(Need to authorize a lot of logins)_
- Browser _(Often need to look things up)_
- Messaging _(Where I get messages about appointments, school, etc...)_
- Messenger _(Where I communicate with all friends and family)_
- Google Tasks _(To-Do list)_
- Play Store _(To get access to the apps that I can't have on the homescreen)_
- Strava _(Workouts)_

But I need room for these apps:  

- MobilePay _(Very used payment system here in Denmark)_
- NemID _(What we use in Denmark for logging into healthcare / payment / other systems)_
- Spotify
- _probably some other thing here that I can't remember_

Minimalism means efficient access to the essentials, which as of right now this homepage can not provide.
