### ISSUE TITLE
Bug: About crashes the whole launcher when no browser is available

### ISSUE THREAD

**Issue by csqn2** [sduduzog/slim-launcher#57]
Hi,
first of all, thanks for your great launcher! It has helped to get my device usage to <1 hour per day (including calls and texting) :)

**Description:** When no web browser is available, selecting the "About Slim" (sometimes also tapped by mistake) option crashes the whole launcher. A "Select launcher" dialog appears, where you have to choose Slim anew to restart it.

**Proposed fix(es):**
For the time being, just check if a web browser is even available. If not, do nothing when selecting the About option (much better than crashing). In the long run, I can already see you are considering revamping the About functionality.

**Details:** I am using your launcher as an attempt to radically cut down mobile device usage. As such I even disabled the web browser on my device and I am using it exclusively to call, text, Signal and mobile banking. The device is an Android One-based Xiaomi A2 Lite running Pie (October patches).

Thanks a lot!

P. S. In your store descriptions, you advertise the launcher only being able to make 5 shorcuts. I can personally set 7. Is this also a bug or a later change?

**Comment by sduduzog** [comment]
Thanks for this @csqn2 I should really cleanup the app and get stuff up to date as soon as possible. A late change came with allowing 7 apps instead of 5. For some reason I haven't updated the app description 🤦‍♂

**Comment by csqn2** [comment]
Ok. Don't worry, I personally think the launcher is perfect as it is. It is definitely _very_ slim and snappy. This is the only bug I noticed.

I don't know why, 7 apps (+ the 3 available from the main screen: clock, phone, camera) works perfect for me. I don't get the people who would like more: you can always make a shortcut to your the store of your choice (Play Store/F-Droid) and launch apps from there if you really need them from time to time.

The main point of your launcher is: there are no fancy colourful icons that "want" us to click them. You have to choose apps you really need and don't use the rest. It's great, keep up the good work! Will buy you a coffee.
