### ISSUE TITLE
Create a standalone website for slim launcher

### ISSUE THREAD

**Issue by sduduzog** [sduduzog/slim-launcher#58]

**Comment by brightknight08** [comment]
what kind of landing page/website are  you thinking about? I think I can help out. If I may, I suggest this to be something that you can also add as the about screen to the app (as stated/requested in issue #67)

**Comment by sduduzog** [comment]
@brightknight08 I just wanna slap anything I can put on it. The about section within the app should live within the app though and not redirect to a link. This is what is currently there https://sduduzog.github.io/slim-launcher/

**Comment by sduduzog** [comment]
@brightknight08 And I think I've made a home for it https://github.com/sduduzog/slim-launcher-website

**Comment by ribab** [comment]
Maybe this can help <https://developer.chrome.com/apps/app_codelab_webview>

> Open External Links With a Webview

**Comment by sduduzog** [comment]
slimlauncher.sduduzog.com

**Comment by emmanuelchucks** [comment]
> https://slimlauncher.sduduzog.com

Link is broken
Change to https://www.slimlauncher.com?
