### ISSUE TITLE
Couple typos in Store description

### ISSUE THREAD

**Issue by maxdevjs** [sduduzog/slim-launcher#7]
[Slim Launcher (Play Store)](https://play.google.com/store/apps/details?id=com.sduduzog.slimlauncher)

`#1 Rename apps that are on your home screen by long pressing on one, in Peferences.`

`Preferences`

---
`#3 (Experimental) Built in dialer for faster launch response time. When activated in Preferences, pong press`

`long`

---

Keep it up, amazing work :D

**Comment by sduduzog** [comment]
You lie! How did those miss me? Or maybe I was too excited to release. Fun fact, I did this rollout on my phone
