### ISSUE TITLE
Improvement to search

### ISSUE THREAD

**Issue by ReleaseTheKnowledge** [sduduzog/slim-launcher#70]
Current behavior:
When you search for an app the search is case sensitive. And is mandating use of symbols like "-".

Example 1: You wanna open andOTP, and when you begin the search and write "An..", the app does not come up. 

Example 2: You wanna open "F-droid", and search for "Fdroid", and it does not come up.

Expected behavior:
Search should be case insensitive.
Ignore "-" so F-droid comes up if you search "fdroid".

**Comment by jkuester** [comment]
@sduduzog I think this issue can be closed since it has been addressed by https://github.com/sduduzog/slim-launcher/pull/81
