### ISSUE TITLE
A few considerations

### ISSUE THREAD

**Issue by maxdevjs** [sduduzog/slim-launcher#8]
I used [Smart Launcher](https://play.google.com/store/apps/details?id=ginlemon.flowerpro) (last version [Smart Launcher 5](https://play.google.com/store/apps/details?id=ginlemon.flowerfree)) for a few years now and really enjoy it. 

Today I switched to [Slim Launcher](https://play.google.com/store/apps/details?id=com.sduduzog.slimlauncher) (okay, testing for now :D), it already offers all I need. So, what is the purpose to mention SL? Well, it offers a **lot** of features, but can also be configured to be a very minimal launcher. 

I will leave here my wish list (independently of implementation difficulty):

- click on date, to open preferred calendar app
- possibility to hide (and show with a gesture, of course) status bar (bottom too? This would get very interesting against Preferences visualization...)
- pack up apps list in a sliding panel (à la Preferences) to further clear the home
- add shortcut to Play Store in Preferences

**Comment by sduduzog** [comment]
Thank you very much for the feedback. 

Your wish list. I like all items seriously. With click on date, I don't know why I didn't do it but I remember considering it.

The status bar was hidden in the back early stages of development. My classmate said he wanted it back 😌 he was my only tester at the time.

**Comment by sduduzog** [comment]
Well this is not the first request to hide it. Someone else asked for it via review on google play

**Comment by maxdevjs** [comment]
At first, could be a simple boolean state (shown/hidden)? No idea if a gesture could be complicated to implement.

**Comment by sduduzog** [comment]
Boolean on preferences will do it. Eith any app thats fullscreen, when you swipe down from the top edge of the screen, the status bar is revealed momentarily. I think this is a system behavior.

**Comment by maxdevjs** [comment]
In fact, a shortcut to Play Store exists in Preferences. I meant one/multiple weird gestures in home. 

If I can ask, how did you start with the project code? Borrowing some starter resources or from scratch?

**Comment by sduduzog** [comment]
From scratch. I was also excited by working with jetpack

**Comment by maxdevjs** [comment]
Interesting... jetpack seems a great deal... are you satisfied?

**Comment by maxdevjs** [comment]
Good points... thank you for clarifying these concepts.

**Comment by maxdevjs** [comment]
I should update my wish list: in fact apps list is already available in Preferences. Would be nice to be able to click on the name to start an app, for example. 

Again, may be a simple boolean to mirror or not the list in home. 

Only real drawback I can currently find: would be probably counterintuitive to the unaware user.
