### ISSUE TITLE
Allow access to a list of all apps

### ISSUE THREAD

**Issue by ploum** [sduduzog/slim-launcher#80]
I know that the point of slim-launcher is to limit the access to any app.

But there are many app you need to access on a quite rare basis: banking app, f-droid, train ticket, bluetooth gadget sync etc. I found it out the hardway when using slim launcher with no clear path to access what I needed.

Other "light launcher" usually offers the ability to launch any app by searching for them. I found it quite interesting because it's cumbersome enough to not have a reflex and still allow for some flexibility.

Is there a plan to add such a feature in Slim-launcher ?

If not, what's the workflow of users when you want to access an app which is not in your favourites?

**Comment by boromisp** [comment]
On my Samsung phone there is an search bar in the app switcher that can be used for this purpose. Without that and the [Edge Panel](https://www.samsung.com/sg/support/mobile-devices/what-is-edge-panel-and-how-to-use-it-on-samsung-mobile-device/) I would never be able to use this launcher. There might be other 3rd party apps that implement similar features?

**Comment by koppen37** [comment]
From what I read in other issues, there are no plans to show a list of all apps. Some ways around it are:

- Use the 7th option as a placeholder, change it using options > Custimise Apps to set the app currently needed.
- Use [KISS launcher](https://f-droid.org/en/packages/fr.neamar.kiss/) as your Assist App and use it to search for a specific app (so long pressing your home buttons opens KISS launcher)
- Personally I use [Simple App Launcher](https://f-droid.org/en/packages/com.simplemobiletools.applauncher/) as my 7th app and add the minimal needed applications to it.

**Comment by jkuester** [comment]
I also found that 7 apps was not feasible for my needs.  However, I really loved Slim Launcher's clean interface.  For awhile I was actually using the Simple App Launcher the same way as @koppen37.  

Since adding access to additional apps seems to go against the Slim Launcher project philosophy and is a feature that is unlikely to be accepted, I ended up forking the project and adding access to all the installed apps in https://github.com/jkuester/unlauncher.

**Comment by sduduzog** [comment]
@jkuester I love your forked app, also thanks for the shoutout on your readme.

Although extending the number of apps will not be something I'll be working on, be on a lookout for https://github.com/sduduzog/slim-launcher/pull/98 which has been on my mind for a very long time.
