### ISSUE TITLE
Possible PRs: rewrite of motionscene, hide camera/clock, search

### ISSUE THREAD

**Issue by koppen37** [sduduzog/slim-launcher#84]
I've been using this launcher for a few weeks now and really like it. Next to that I wanted to learn some Kotlin for android, so this seemed like a good app the experiment with. I really liked the coding style, which made it easy to apply some changes.

I now have a  [personal branch](https://github.com/koppen37/slim-launcher/tree/app_search) that has a bunch of changes that probably should become different PRs if you like them, however some of them will probably never end up in the app (like a search -> launch function). So I was curious which of the following additions you might be interested in, so that I can make a proper PR for it (if you like the implementation as well). 

* Hide elements on the homescreen
  * Rewrites `home_fragment.xml, home_motion_scene.xml` (and removes `home_motion_{01,02}.xml`)
  * Needed this to have constraints to which we add `<PropertySet app:visibilityMode = "ignore" /> `for Views that should be hideable
    * Otherwise `visibility = View.INVISIBILE` seemed to get ignored
  * Extra screen in options to toggle the views (see gif below)

* Filter bar at the bottom of the screen when adding apps
  * Small and simple change, but I prefer it

* Search option
  * Adds a search button next to "Options" 
  * Renamed the `CustomiseAppsFragment` to `AppFilerFragment` and made abstract
  * Both the `CustomiseAppsFragment` and `SearchFragment` use this class, only differences:
    * Search doesn't show a list of apps on an empty query, otherwise it would give a complete applist to launch from
    * Search launches the application instead of adding it

Again, I know that some of these might give users to much freedom in launching other apps and I have no clue whether my implementation actually make sense design wise.

Below a little preview of all the changes that are in my app_search branch:

![app-search-branch](https://user-images.githubusercontent.com/7763136/87191005-d84d2f80-c2f3-11ea-96b3-f9576ec16737.gif)

**Comment by pirol541** [comment]
This is awesome work, @koppen37 ! The option to hide the clock/phone/camera on the home screen is exactly what I miss in the current launcher.

@sduduzog Any chance we could get this option merged in the next version?

**Comment by koppen37** [comment]
Thanks for the kind words. 

A small update from my side, I already started working on a pull request for that feature on [this](https://github.com/koppen37/slim-launcher/tree/hide_elements) branch. There are some things I want to take a look at before actually opening the pull request, but most of the functionality is already there.

**Comment by sduduzog** [comment]
@koppen37 This is wonderful, I want to spend some time looking at your branch as see how we'll go about merging in some of these changes in the app.

**Comment by koppen37** [comment]
Good to hear @sduduzog! The app_search branch has probably got a bit messy with all the different changes in it, so let me know if you want me to prepare a separate branch for any of the other changes as well (just like the hide_elements branch).

**Comment by sduduzog** [comment]
I've been trying to sort these PRs out one by one. It's weird that this was setup months ago now hahaha.

I'm slowly checking out these PRs and creating releases from them. Hopefully I'll be done in less than a week
