### ISSUE TITLE
Can't disable auto rotate

### ISSUE THREAD

**Issue by micwoj92** [sduduzog/slim-launcher#86]
Hello @sduduzog ,
I've been using and enjoying this launcher for long time now, but today I updated to 2.4.8 from F-Droid and I can't see an option to disable autorotation. It even does that when setting is disabled in Android. Huge step backwards. Android 9, Huawei FIG-LX1

**Comment by sduduzog** [comment]
I see what happened there, I pushed a fix for it but the semver versioning wasn't fixed from my part

**Comment by micwoj92** [comment]
Thank you. Is there any eta for new release? I know I could build from master, but I'd rather keep F-Droid version installed so I can update without hassle in future.

**Comment by sduduzog** [comment]
Could have been really quick but I've migrated my workspace to a new pc so hopefully 1-2 days

**Comment by laundmo** [comment]
this is still an issue, i have the latest f-droid version, and the app still auto-rotates even though ive turned rotation off in my phones settings.

the best solution imo would be to have the app respext the phones rotation settibgs, and then allow for overriding that with the option to always stay in portrait mode or always in landscape

**Comment by micwoj92** [comment]
@laundmo that issue was made after last version in F-Droid. Notice that it still didnt push new one to F-Droid hence I did not close it. I Will close when the fix lands in F-Droid (so probably with next version)

**Comment by sduduzog** [comment]
@laundmo @micwoj92 I messed up a fix for this during versioning, I'm using gradle play publisher and how it handles auto versioning is funky in the project. The fix is so long overdue though

**Comment by micwoj92** [comment]
Now on F-Droid is 2.4.14 and bug is fixed there. Thanks @sduduzog
