### ISSUE TITLE
Alternative Download Source

### ISSUE THREAD

**Issue by IzzySoft** [sduduzog/slim-launcher#9]
Currently this launcher is only available via Playstore – thus leaving everybody out who cannot (or does not want to) access that. Would you mind attaching the APK to its release? Or maybe even have it available via [F-Droid](https://f-droid.org/)? If you never heard of F-Droid before (shameless self-promotion coming now), there's a detailed introduction on my site: [F-Droid: The privacy-friendly alternative to Google Play Store](https://android.izzysoft.de/catmin/articles/named/fdroid-intro-1?lang=en) :blush:

**Comment by IzzySoft** [comment]
@sduduzog ping?

**Comment by sduduzog** [comment]
Oh thanks man I forgot about this. I wanted to figure out automation for builds first

**Comment by IzzySoft** [comment]
Thanks for your response, @sduduzog! Let me know if you need help with getting your app to F-Droid (disclosure: I'm one of the maintainers there) or decided to go with attaching the APK to `releases/` first (and have one there, so I could for a start serve that via [my repo](https://apt.izzysoft.de/fdroid/repo)).

Meanwhile: Fingers crossed for the automation task! :crossed_fingers:

**Comment by sduduzog** [comment]
Ok, I've been reading up on some docs and a few FAQS on fdroid. I'll definitely need some time to figure everything out. I've joined the forum though.

**Comment by IzzySoft** [comment]
Just let me know how I can help you. I gladly initiate the process by [filing an "RFP"](https://gitlab.com/fdroid/rfp/issues) (Request For Packaging) if you want, which would be followed by one of our team¹ trying to integrate it (after our scanner confirmed there are no "inacceptable components" inside :wink:).

As you added the "help wanted" label: If you need help other than that, please indicate how we can help you.

----

¹ <sub>Disclosure: I'm one of the F-Droid maintainers</sub>

**Comment by sduduzog** [comment]
Yea I've been stumbling around and I'm back here. I'd appreciate it if you did file an RFP for me

**Comment by IzzySoft** [comment]
OK, [feedback from our bot](https://gitlab.com/fdroid/rfp/issues/873#note_133172174): It's good to go. But it found out there's some minor security issue with your gradle you might wish to fix :wink: (not affecting F-Droid builds but your own)

**Comment by Rudloff** [comment]
Hello,

Building v2.2.0 for F-Droid fails with the following error:
```
> Task :app:kaptReleaseKotlin
e: /home/pierre/www/fdroiddata/build/com.sduduzog.slimlauncher/app/src/main/java/com/sduduzog/slimlauncher/MainActivity.kt: (15, 109): Unresolved reference: OnNavigatedListener
e: /home/pierre/www/fdroiddata/build/com.sduduzog.slimlauncher/app/src/main/java/com/sduduzog/slimlauncher/MainActivity.kt: (50, 19): Unresolved reference: addOnNavigatedListener
e: /home/pierre/www/fdroiddata/build/com.sduduzog.slimlauncher/app/src/main/java/com/sduduzog/slimlauncher/MainActivity.kt: (80, 5): 'onNavigated' overrides nothing
> Task :app:compileReleaseKotlin FAILED
```
But this seems to be fixed on master.

@sduduzog Are you planning on tagging a new release?

**Comment by Rudloff** [comment]
2.2.5 builds correctly, thanks!

**Comment by sduduzog** [comment]
So what are the next steps from here?

**Comment by Rudloff** [comment]
I opened a merge request and it is waiting to be reviewed: https://gitlab.com/fdroid/fdroiddata/merge_requests/4346

**Comment by sduduzog** [comment]
I'm closing the issue, I'm assuming all went well. I do however wish to contribute to F-droid, I'm not sure how to begin. @IzzySoft

**Comment by IzzySoft** [comment]
@sduduzog Yes, thanks: that MR @Rudloff mentioned was successfully merged 5min ago, so your app should show up in F-Droid soon. If you have more questions, don't hesitate to ask; we'll help you as best as we can.
